name: Example documentation

on:
  push:
    branches:
      - docs

jobs:
  # Build the documentation
  build:
    runs-on: windows-latest # Required by DocFX
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        # with:
        #   submodules: true

      - name: Dotnet Setup
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.x
      
      - name: Dotnet install
        run: dotnet tool install -g docfx
    
      - name: Dotnet Update
        run: dotnet tool update -g docfx

    #  - name: Install DocFX
    #    run: choco install -y docfx --version=2.59.4

      - name: Use README.md as index.md
        run: cp README.md Documentation~/index.md

      - name: Build
        run: docfx Documentation~/docfx.json

      # Upload the generated documentation
      - name: Upload site artifact
        uses: actions/upload-artifact@v4
        with:
          name: _site
          path: ./_site # Must equals the 'build.dest' value on your docfx.json

  # Deploy the generated documentation to the gh-pages branch
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        # with:
        #   submodules: true

      # Download the generated documentation
      - name: Download site artifact
        uses: actions/download-artifact@v4
        with:
          name: _site
          path: ./_site

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./_site
          allow_empty_commit: true
          cname: tmpeffects.luca3317.dev
